def tutorial():
    print("Hello and welcome to Path:Unknown\n"
          "\n"
          "In this game you will spawn at a random airport, anywhere in the world.\n"
          "Your objective is to reach a specific airport in the minimum amount of attempts possible.\n"
          "An attempt is counted everytime you reach a different airport.\n"
          "Instructions on how to move can be found after starting a game.\n"
          "\n"
          "The username you just imputed saves your session data.\n"
          "Be sure to use the same one to save/load previous progress.\n"
          "After this you will be prompted with a settings menu, where you customize your game.\n"
          "\n"
          "Game Difficulty: Easy, Medium or Hard\n"
          "This parameter affects the type of airports that appear in your game session.\n"
          "— Easy: only large airports (total: 451)\n"
          "— Medium: large and medium airports (total: 5,191)\n"
          "— Hard: large, medium and small airports (total: 43,482\n"
          "\n"
          "Target Distance: Near, Average or Far\n"
          "This parameter affects the distance between the starting and the target airports.\n"
          "— Near: between 1,000 and 5,000 kilometers\n"
          "— Average: between 5,000 and 11,000 kilometers\n"
          "— Far: above 11,000 kilometers\n"
          "\n"
          "Modifiers: Overwater and Hel Mode (Work in Progress)\n"
          "This parameters add additional elements to your gameplay.\n"
          "— Overwater: you are flying a seaplane and can now land in seaplane bases\n"
          "— Hel Mode: you are flying a helicopter and can now land in helipads\n"
          "\n"
          "Note: You can combine multiple modifiers to enhance your experience!\n")


def game_credits():
    print("\nThis project was developed by:\n"
          "— Daniil Lukin\n"
          "— Egzon Barja\n"
          "— Ricardo de Sousa\n"
          "— Théo Sampaio\n"
          "— Upeksha Liyanage\n")
